apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  creationTimestamp: null
  name: {{ .Values.kubeState.name -}}-bind
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.kubeState.name }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.kubeState.name }}
  namespace: {{ .Values.kubeState.namespace }}