  loki.yaml: |
    auth_enabled: false

    server:
      http_listen_port: 3100
      log_level: info

    common:
      storage:
        s3:
          s3: "s3://loki"
          access_key_id: '${S3_ACCESS_KEY}'
          secret_access_key: '${S3_SECRET_KEY}'
          insecure: true
          s3forcepathstyle: true
          endpoint: 'loki-minio.mon.svc.cluster.local:9000'
      ring:
        kvstore:
          store: inmemory
      replication_factor: 1

    ingester:
      wal:
        enabled: false
        dir: /loki/index/wal
      lifecycler:
        address: 127.0.0.1
        ring:
          kvstore:
            store: inmemory
          replication_factor: 1
      chunk_idle_period: 3m
      chunk_retain_period: 1m


    schema_config:
      configs:
      - from: 2020-10-24
        store: boltdb-shipper
        object_store: s3
        schema: v11
        index:
          prefix: index_
          period: 24h

    storage_config:
      boltdb_shipper:
        active_index_directory: /loki/index
        cache_location: /loki/index_cache
      aws:
        s3: s3://loki
        bucketnames: "loki"
        endpoint: 'loki-minio.mon.svc.cluster.local:9000'
        access_key_id: '${S3_ACCESS_KEY}'
        secret_access_key: '${S3_SECRET_KEY}'
        insecure: true
        s3forcepathstyle: true
        http_config:
          idle_conn_timeout: 300s
          response_header_timeout: 0s
          insecure_skip_verify: true

    limits_config:
      retention_period: 14d
      allow_structured_metadata: false
      reject_old_samples: true
      reject_old_samples_max_age: 168h

    compactor:
      working_directory: /loki/compactor

