apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: victoria-single
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  - services
  - endpoints
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - create
  - list
  - update
  - patch
  - delete
- nonResourceURLs:
  - /metrics
  verbs:
  - get
- nonResourceURLs:
  - /healthz
  verbs:
  - get