apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: victoria-single
  name: victoria-single
  namespace: mon
spec:
  podManagementPolicy: OrderedReady
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: victoria-single
  serviceName: victoria-single-svc
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: victoria-single
    spec:
      automountServiceAccountToken: true
      containers:
      - args:
        - --retentionPeriod=7
        - --storageDataPath=/var/lib/data
        - -promscrape.config=/etc/victoria-single/scrape.yml
        - -promscrape.config.strictParse=false
        - --envflag.enable=true
        image: victoriametrics/victoria-metrics:v1.95.1
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 10
          httpGet:
            path: /health
            port: 8428
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 5
        name: victoria-single
        ports:
        - containerPort: 8428
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: http
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 15
          successThreshold: 1
          timeoutSeconds: 5
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/lib/data
          name: data
        - mountPath: /etc/victoria-single
          name: scrapeconfig
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: victoria-single-sa
      serviceAccountName: victoria-single-sa
      terminationGracePeriodSeconds: 60
      volumes:
      - configMap:
          defaultMode: 420
          name: victoria-single-config
        name: scrapeconfig
  updateStrategy:
    rollingUpdate:
      partition: 0
    type: RollingUpdate
  volumeClaimTemplates:
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      creationTimestamp: null
      name: data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
      volumeMode: Filesystem
    status:
      phase: Pending