apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: mon
  labels:
    app: vmstorage-single
  name: victoria-metrics-single
spec:
  serviceName: victoria-metrics-single
  selector:
    matchLabels:
      app: vmstorage-single
  replicas: 1
  podManagementPolicy: OrderedReady
  template:
    metadata:
      labels:
        app: vmstorage-single
    spec:
      automountServiceAccountToken: true
      containers:
        - name: victoria-metrics-single
          image: victoriametrics/victoria-metrics:v1.95.1
          imagePullPolicy: "IfNotPresent"
          args:
            - "--retentionPeriod=7"
            - "--storageDataPath=/storage"
            - --envflag.enable=true
          ports:
            - name: http
              containerPort: 8428
          livenessProbe:
            failureThreshold: 10
            httpGet:
              path: /health
              port: 8428
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 5
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 15
            timeoutSeconds: 5
          resources:
            limits:
              cpu: 100m
              memory: 256Mi
            requests:
              cpu: 50m
              memory: 128Mi
          volumeMounts:
            - name: server-volume
              mountPath: /storage
              subPath:
      terminationGracePeriodSeconds: 60
      volumes:
  volumeClaimTemplates:
    - metadata:
        name: server-volume
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: "10Gi"

