# Default values for kube-state.
kubeState:
  name: kube-state-metrics
  namespace: mon
  service:
    name: telemetry
    nameMetrics: http-metrics
  image:
    repo: k8s.gcr.io
    tag: v2.5.0
    name: kube-state-metrics/kube-state-metrics
  resources:
    limit_cpu: 200m
    request_cpu: 50m
    limit_memory: 500Mi
    request_memory: 200Mi


# Default values for node-exporter.
nodeExporter:
  enable: true
  name: node-exporter
  labels: node-exporter
  namespace: mon
  image:
    repo: prom
    name: node-exporter
    tag: v1.5.0
  resources:
    limit_cpu: 100m
    request_cpu: 50m
    limit_memory: 200Mi
    request_memory: 100Mi

# Default values for prometheus.
prometheus:
  name: prometheus
  namespace: mon
  image:
    repo: prom
    name: prometheus
    tag: v2.40.2
  configMapName: prometheus-config
  retentionPeriod: 2h
  storageClass: lvm-ssd
  storagePvc: 10Gi
  resources:
    limit_cpu: 1
    request_cpu: 500m
    limit_memory: 1024Mi
    request_memory: 1024Mi
####### config can be empty/all/federate/my-values (test.yaml file in root direcroty) ############   
  config: empty
  


alertmanager:
  enable: true
  name: alertmanager
  namespace: mon
  image:
    repo: prom
    name: alertmanager
    tag: v0.24.0
  resources:
    limit_cpu: 500m
    request_cpu: 200m
    limit_memory: 512Mi
    request_memory: 256Mi
  storageClass: lvm-ssd
  storagePvc: 1Gi