apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: mon
  labels:
    name: prometheus-config
data:
  prometheus.yml: |-
    global:
      scrape_interval: 30s
      evaluation_interval: 30s
    remote_write:
      - url: "http://vminsert.mon.svc.cluster.local:8480/insert/4/prometheus"
        queue_config:
          max_samples_per_send: 10000
          capacity: 20000
          max_shards: 30
    scrape_configs:
      - job_name: 'node-exporter'
        kubernetes_sd_configs:
          - role: endpoints
        relabel_configs:
        - source_labels: [__meta_kubernetes_endpoints_name]
          regex: 'node-exporter'
          action: keep
      - job_name: 'kube-state-metrics'
        static_configs:
          - targets: ['kube-state-metrics.kube-system.svc.cluster.local:8080']
