apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: prometheus
  name: prometheus
  namespace: mon
spec:
  podManagementPolicy: OrderedReady
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: prometheus
  serviceName: prometheus
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: prometheus
        component: prometheus
    spec:
      securityContext:
        runAsUser: 65534
        runAsGroup: 65534
        fsGroup: 65534
        runAsNonRoot: true
      containers:
      - args:
        - --web.enable-lifecycle
        - --storage.tsdb.retention.time=2h
        - --config.file=/prometheus.yaml
        - --storage.tsdb.path=/var/lib/prom/
        image: prom/prometheus:v2.48.0
        imagePullPolicy: IfNotPresent
        name: prometheus
        resources:
          limits:
            cpu: "3"
            memory: 12G
          requests:
            cpu: 200m
            memory: 1G
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/prometheus/
          name: configs-files
        - mountPath: /var/lib/prom/
          name: data-prometheus
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      serviceAccount: prometheus
      serviceAccountName: prometheus
      terminationGracePeriodSeconds: 30
      volumes:
      - name: configs-files
        projected:
          defaultMode: 420
          sources:
          - configMap:
              name: prometheus-config
  updateStrategy:
    type: RollingUpdate
  volumeClaimTemplates:
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      creationTimestamp: null
      labels:
        app: prometheus
      name: data-prometheus
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 25Gi
      storageClassName: standard
      volumeMode: Filesystem
    status:
      phase: Pending