apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: vmauth
  name: vmauth
  namespace: mon
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: vmauth
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: vmauth
        component: vmauth
        stack: monitoring
    spec:
      containers:
      - args:
        - -auth.config=/tmp/config.yaml
        image: victoriametrics/vminsert:v1.77.2-cluster
        imagePullPolicy: IfNotPresent
        name: vmauth
        resources:
          limits:
            cpu: 500m
            memory: 512M
          requests:
            cpu: 50m
            memory: 128M
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /tmp/
          name: vmauth-config
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: auth-config
        name: vmauth-config