
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-pvc
  finalizers:
    - kubernetes.io/pvc-protection
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
