{{- if .Values.alertmanager.enable }}
apiVersion: v1
data:
  alertmanager.yaml: |2

    global:
    templates:
    - '/etc/alertmanager/telegram.tmpl'
    receivers:
      {{- if eq .Values.config.alertmanager.config.type "telegram" }}
      - name: telegram_default
        telegram_configs:
          - send_resolved: true ##hardcode
            chat_id: -1111 ##hardcode
            bot_token: 'token' ##hardcode
            api_url: 'https://api.telegram.org'
            parse_mode: HTML
            message: '{{ "{{"  }} template "telegram.custom.message" . }}'
      {{- range .Values.config.alertmanager.config.bot }}
      - name: {{ .name  }}
        telegram_configs:
          - send_resolved: {{ .send_resolved | default "true" }}
            chat_id: {{ .chat_id }}
            bot_token: {{ .bot_token | quote }}
            api_url: 'https://api.telegram.org'
            parse_mode: HTML
            message: '{{ "{{"  }} template "telegram.custom.message" . }}' 
      {{- end }}
      {{- end }}
    route:
      receiver: 'telegram_default'
      group_wait: 30s
      group_interval: 1m
      repeat_interval: 10h
      group_by: ['...']
      routes:
        {{- if eq .Values.config.alertmanager.config.type "telegram" }}
        {{- range .Values.config.alertmanager.config.bot }}
        - receiver: {{ .name }}
          group_wait: 10s
          matchers:
          {{- range $key, $val := .routeLabel }}
          {{- range $key2, $val2 := $val }}
          - {{ $key2 }} = {{ $val2 }}
          {{- end }}
          {{- end }}
        {{- end }}
        {{- end }}
kind: ConfigMap
metadata:
  name: {{ .Values.alertmanager.name -}}-config
  namespace: {{ .Values.namespace }}
{{- end }}
