apiVersion: v1
kind: Service
metadata:
  name: alertmanager
  namespace: mon
spec:
  ports:
  - name: api
    port: 9093
    protocol: TCP
    targetPort: 9093
  - name: cluster-peer
    port: 9094
    protocol: TCP
    targetPort: 9094
  selector:
    app: alertmanager
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}