{{- if .Values.alertmanager.enable }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.alertmanager.name -}}-svc
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - name: {{ .Values.alertmanager.name }}
    port: 9093
    protocol: TCP
    targetPort: 9093
  - name: cluster-peer
    port: 9094
    protocol: TCP
    targetPort: 9094
  selector:
    app: {{ .Values.alertmanager.name }}
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
{{- end }}