{{- if .Values.alertmanager.enable }}
apiVersion: v1
data:
  manager.yaml: ""
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: {{ .Values.alertmanager.name }}-template
  namespace: {{ .Values.alertmanager.namespace }}
{{- end }}