{{ if .Values.victoriaSingle.enable }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app: {{ .Values.victoriaSingle.name }}
  name: {{ .Values.victoriaSingle.name -}}-bind
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.victoriaSingle.name }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.victoriaSingle.name -}}-sa
  namespace: {{ .Values.namespace }}
{{ end }}