{{ if .Values.victoriaSingle.enable }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: {{ .Values.victoriaSingle.name }}
  name: {{ .Values.victoriaSingle.name }}
  namespace: {{ .Values.namespace }}
spec:
  podManagementPolicy: OrderedReady
  replicas: {{ .Values.victoriaSingle.replicas }}
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: {{ .Values.victoriaSingle.name }}
  serviceName: {{ .Values.victoriaSingle.name -}}-svc
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: {{ .Values.victoriaSingle.name }}
    spec:
      automountServiceAccountToken: true
      containers:
      - args:
        - --retentionPeriod={{- .Values.victoriaSingle.args.retentionPeriod | default "1" }}
        - --storageDataPath={{- .Values.victoriaSingle.args.storagePath | default "/var/lib/data" }}
        - -promscrape.config=/etc/victoria-single/scrape.yml
        - --envflag.enable=true
        {{- if .Values.victoriaSingle.extArgs }}
        {{- range .Values.victoriaSingle.extArgs }}
        - {{ . }}
        {{- end }}
        {{- end }}
        image: {{ .Values.victoriaSingle.image.repo -}}/{{- .Values.victoriaSingle.image.name -}}:{{- .Values.victoriaSingle.image.tag }}
        imagePullPolicy: IfNotPresent
        {{- if .Values.victoriaSingle.probe.enable }}
        livenessProbe:
        {{- with .Values.victoriaSingle.probe }}
          failureThreshold: {{ .failureThreshold | default "3" }}
          httpGet:
            path: /health
            port: 8428
            scheme: HTTP
          initialDelaySeconds: {{ .initialDelaySeconds | default "30"}}
          periodSeconds: {{ .periodSeconds | default "15" }}
          successThreshold: {{ .successThreshold | default "1" }}
          timeoutSeconds: {{ .timeoutSeconds  | default "5" }}
        {{- end }}
        {{- end }}
        name: {{ .Values.victoriaSingle.name }}
        ports:
        - containerPort: 8428
          name: http
          protocol: TCP
        {{- if .Values.victoriaSingle.probe.enable }}
        readinessProbe:
        {{- with .Values.victoriaSingle.probe }}
          failureThreshold: {{ .failureThreshold | default "3" }}
          httpGet:
            path: /health
            port: http
            scheme: HTTP
          initialDelaySeconds: {{ .initialDelaySeconds | default "30"}}
          periodSeconds: {{ .periodSeconds | default "15" }}
          successThreshold: {{ .successThreshold | default "1" }}
          timeoutSeconds: {{ .timeoutSeconds  | default "5" }}
        {{- end }}
        {{- end }}
        {{- if .Values.victoriaSingle.resources }}
        resources:
        {{- with .Values.victoriaSingle.resources }}
          limits:
            cpu: {{ .limit.cpu  | default "1" }}
            memory: {{ .limit.memory | default "1200Mi" }}
          requests:
            cpu: {{ .request.cpu | default "50m" }}
            memory: {{ .request.memory | default "100Mi" }}
        {{- end }}
        {{- end }}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: {{ .Values.victoriaSingle.args.storagePath | default "/var/lib/data" }}
          name: data
        - mountPath: /etc/victoria-single
          name: scrapeconfig
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: {{ .Values.victoriaSingle.name -}}-sa
      serviceAccountName: {{ .Values.victoriaSingle.name -}}-sa
      terminationGracePeriodSeconds: 60
      volumes:
      - configMap:
          defaultMode: 420
          name: {{ .Values.victoriaSingle.name -}}-config
        name: scrapeconfig
  updateStrategy:
    rollingUpdate:
      partition: 0
    type: RollingUpdate
  volumeClaimTemplates:
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      creationTimestamp: null
      name: data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: {{ .Values.victoriaSingle.storage.capacity | default "10Gi" }}
      volumeMode: Filesystem
      storageClassName: {{ .Values.victoriaSingle.storage.class }}
    status:
      phase: Pending
{{ end }}