{{ if .Values.victoriaSingle.enable }}
apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.victoriaSingle.name }}
  name: {{ .Values.victoriaSingle.name }}-svc
spec:
  ports:
    - name: http
      port: 8428
      protocol: TCP
      targetPort: http
  selector:
    app: {{ .Values.victoriaSingle.name }}
{{ end }}