apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app":"vmauth"},"name":"vmauth","namespace":"mon"},"spec":{"clusterIP":"None","ports":[{"name":"auth","port":8427,"protocol":"TCP","targetPort":8427}],"selector":{"app":"vmauth"},"type":"ClusterIP"}}
  creationTimestamp: "2022-01-28T10:28:15Z"
  labels:
    app: vmauth
  name: vmauth
  namespace: mon
  resourceVersion: "384318874"
  uid: 70ee322e-10fd-40ad-b6b5-715f178f205d
spec:
  clusterIP: None
  clusterIPs:
  - None
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: auth
    port: 8427
    protocol: TCP
    targetPort: 8427
  selector:
    app: vmauth
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
