apiVersion: v1
kind: Service
metadata:
  labels:
    app: vmauth
  name: vmauth
  namespace: mon
spec:
  ports:
  - name: auth
    port: 8427
    protocol: TCP
    targetPort: 8427
  selector:
    app: vmauth
  sessionAffinity: None
  type: ClusterIP
