# # Default non system values

namespace: mon

config:
  scrape:
    kubernetesCadvisor: true
    kubernetesKubelet: true
    kubernetesPods: true
    database: false
    blackboxUrl:
      enable: false
      urls: {}
        #- https://google.com
        #- https://my-url
  

###    kubernetesPods annotations ---> just add this annotation into pods
####   annotations:
#        prometheus.io/scrape: "true"
#        prometheus.io/metric_path: /actuator/prometheus
#        prometheus.io/port: "8080"
####
####  database ----> just add label  database_metrics_enabled: true


### Default values for blackbox

blackbox:
  enable: false
  image:
    tag: v0.23.0
    repo: prom
    name: blackbox-exporter
  name: blackbox-exporter
  imagePullSecrets: {}
    ##- name-secret
  args: {} 
    ##- extra-args
  strategy:
    type: RollingUpdate   #Recreate
    maxUnavailable: 0
  resources:
    limit:
      cpu: 200m
      memory: 200Mi
    request:
      cpu: 50m
      memory: 50Mi


### Default values  for kube-state-metrics

kubeMetrics:
  enable: false
  name: kube-state-metrics
  imagePullSecrets: {}
    ##- name-secret
  replicas: 1
  image:
    repo: registry.k8s.io
    name: kube-state-metrics/kube-state-metrics
    tag: v2.10.0
  resources:
    limit:
      cpu: 200m
      memory: 500Mi
    request:
      cpu: 100m
      memory: 250Mi
  security: true
  probe: 
    enable: true
    #initialDelaySeconds 5
    #timeoutSeconds 5



### Default values for node-exporter

nodeExporter:
  enable: false
  name: node-exporter
  imagePullSecrets: {}
    ##- name-secret
  resources:
    limit:
      cpu: 250m
      memory: 180Mi
    request:
      cpu: 100m
      memory: 150Mi
  args: {}
  # - extra-args
  image:
    repo: quay.io
    name: prometheus/node-exporter
    tag: v1.7.0
  strategy:
    maxUnavailable: 1
    type: Recreate  #RollingUpdate  Recreate



#### Default values for pushgateway

pushgateway:
  enable: false
  name: pushgateway
  imagePullSecrets: {}
    ##- name-secret
  replicas: 1
  image:
    repo: prom
    name: pushgateway
    tag: v1.6.1
  resources:
    limit:
      cpu: 250m
      memory: 380Mi
    request:
      cpu: 100m
      memory: 150Mi
  strategy:
    type: RollingUpdate   #Recreate
    maxUnavailable: 0




### Default values for vm-single
victoriaSingle:
  enable: false
  name: victoria-single
  replicas: 1
  image:
    repo: victoriametrics
    name: victoria-metrics
    tag: v1.95.1
  resources:
    limit:
      cpu: 250m
      memory: 380Mi
    request:
      cpu: 100m
      memory: 150Mi
  storage:
    class: standart
    capacity: 10Gi
  probe:
    enable: true
    #initialDelaySeconds: 30
    #periodSeconds: 15
    #successThreshold: 1
    #timeoutSeconds: 5
    #failureThreshold: 3
  args:
    retentionPeriod: 7
    storagePath: "/var/lib/victoria-single/data"
  extArgs:
    - -loggerLevel=WARN
    - -promscrape.config.strictParse=false



### Default values for prometheus

prometheus:
  enable: false
  name: prometheus







#### Default values for vmauth
vmauth:
  enable: false
  name: vmauth


#### Default values for vminsert
vminsert:
  enable: false
  name: vminsert
  replicas: 1
  image:
    repo: victoriametrics
    name: vminsert
    tag: v1.77.2-cluster
  strategy:
    type: RollingUpdate   #Recreate
    maxUnavailable: 0
  resources:
    limit:
      cpu: 500m
      memory: 750Mi
    request:
      cpu: 100m
      memory: 250Mi
  args: {}
    ##- -extra-args
    ### storage !!!!


#### Default values for vmselect
vmselect:
  enable: false
  name: vmselect
  replicas: 1
  strategy:
    type: RollingUpdate   #Recreate
    maxUnavailable: 0
  resources:
    limit:
      cpu: 500m
      memory: 750Mi
    request:
      cpu: 100m
      memory: 250Mi
  args: {}
    #- -extra-args
  image:
    repo: victoriametrics
    name: vmselect
    tag: v1.77.2-cluster
#### storage!!!

#### Default values for vmstorage
vmstorage:
  enable: true
  name: vmstorage
  replicas: 1
  resources:
    limit:
      cpu: 1
      memory: 1250Mi
    request:
      cpu: 300m
      memory: 550Mi
  args:
    retentionPeriod: 7
    storagePath: "/var/lib/vmstorage/data"
  extArgs:
    - -loggerLevel=WARN
    - -memory.allowedPercent=80
  image:
    repo: victoriametrics
    name: vmstorage
    tag: v1.77.2-cluster
  storage:
    class: standart
    capacity: 10Gi


#### Default values for grafana
grafana:
  enable: false
  name: grafana

#### Default values for alertmanager

alertmanager:
  enable: false
  name: alertmanager


# Default values for prometheus.
# prometheus:
#   name: prometheus
#   image:
#     repo: prom
#     name: prometheus
#     tag: v2.40.2
#   configManName: prometheus-config
#   retentionPeriod: 2h
#   storageClass: lvm-ssd
#   storagePvc: 1Gi
#   resources:
#     limit_cpu: 400m
#     request_cpu: 100m
#     limit_memory: 800Mi
#     request_memory: 424Mi
# ####### config can be empty/all/federate/my-values (test.yaml file in root direcroty) ############   
#   config: empty
  

# Default values for alertmanager
# alertmanager:
#   enable: true
#   template: true
#   name: alertmanager
#   image:
#     repo: prom
#     name: alertmanager
#     tag: v0.24.0
#   resources:
#     limit_cpu: 500m
#     request_cpu: 200m
#     limit_memory: 512Mi
#     request_memory: 256Mi
#   storageClass: lvm-ssd
#   storagePvc: 1Gi

# Default values for grafana

# grafana:
#   enable: true
#   name: grafana
#   secret:
#     user: admin
#     pass: admin
#   pvc:
#     name: grafana
#     storage: 1G
#     storageClass: standart
#   serviceLb: true
