{{- if .Values.grafana.enable }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.grafana.name -}}-pvc
  namespace: {{ .Values.namespace }}
  finalizers:
    - kubernetes.io/pvc-protection
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: {{ .Values.grafana.storage.capacity | default "1Gi" }}
  storageClassName: {{ .Values.storageclass | default .Values.alertmanager.storage.class | default "standard" }}
{{- end }}