{{- if .Values.grafana.enable }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.grafana.name -}}-user
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  admin-user: admin
  admin-password: admin123
{{- end }}