apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app":"vminsert"},"name":"vminsert","namespace":"mon"},"spec":{"clusterIP":"None","ports":[{"name":"insert","port":8480,"protocol":"TCP","targetPort":8480}],"selector":{"app":"vminsert"},"type":"ClusterIP"}}
  creationTimestamp: "2022-01-28T10:28:14Z"
  labels:
    app: vminsert
  name: vminsert
  namespace: mon
  resourceVersion: "384318830"
  uid: 00471c34-b9ac-44c5-a5d0-408c15172851
spec:
  clusterIP: None
  clusterIPs:
  - None
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: insert
    port: 8480
    protocol: TCP
    targetPort: 8480
  selector:
    app: vminsert
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}