{{- if .Values.grafana.enable }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.grafana.name }}
type: Opaque
stringData:
  admin-user: {{ .Values.grafana.secret.user }}
  admin-password: {{ .Values.grafana.secret.pass }}
{{- end }}