apiVersion: v1
data:
  prometheus.yml: |-
    global:
      scrape_interval: 30s
      evaluation_interval: 30s
    remote_write:
      - url: "http://vminsert.mon.svc.cluster.local:8480/insert/1/prometheus"
        queue_config:
          max_samples_per_send: 10000
          capacity: 20000
          max_shards: 30
    scrape_configs:
      - job_name: 'node-exporter'
        static_configs:
          - targets: ['node-exporter.mon.svc.cluster.local:9100']
      - job_name: 'kube-state-metrics'
        static_configs:
          - targets: ['kube-state-metrics.mon.svc.cluster.local:8080']
kind: ConfigMap
metadata:
  labels:
    name: prometheus-config
  name: prometheus-config
  namespace: mon
