apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: vminsert
  name: vminsert
  namespace: mon
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: vminsert
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: vminsert
        component: vminsert
        stack: monitoring
    spec:
      containers:
      - args:
        - --envflag.enable=true
        - --storageNode=vmstorage.mon.svc.cluster.local:8400
        image: victoriametrics/vminsert:v1.77.2-cluster
        imagePullPolicy: IfNotPresent
        name: vminsert
        resources:
          limits:
            cpu: "2"
            memory: 2G
          requests:
            cpu: 100m
            memory: 256M
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
