{{- if .Values.vminsert.enable }}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.vminsert.name }}
  name: {{ .Values.vminsert.name }}
  namespace: {{ .Values.namespace }}
spec:
  progressDeadlineSeconds: 600
  replicas: {{ .Values.vminsert.replicas }}
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: {{ .Values.vminsert.name }}
  strategy:
  {{- if eq .Values.vminsert.strategy.type "RollingUpdate" }}
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: {{ .Values.vminsert.strategy.maxUnavailable }}
    type: RollingUpdate
  {{- end }}
  {{- if eq .Values.vminsert.strategy.type "Recreate" }}
    type: Recreate
  {{- end }}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: {{ .Values.vminsert.name }}
        stack: monitoring
    spec:
      containers:
      - args:
        - --envflag.enable=true
        - --storageNode={{- .Values.vmstorage.name -}}-svc.{{- .Values.namespace -}}.svc.cluster.local:8400
        {{- if .Values.vminsert.args }}
        {{- range .Values.vminsert.args }}
        - {{ . }}
        {{- end }}
        {{- end }}
        image: {{ .Values.vminsert.image.repo -}}/{{- .Values.vminsert.image.name -}}:{{- .Values.vminsert.image.tag }}
        imagePullPolicy: IfNotPresent
        name: {{ .Values.vminsert.name }}
        {{- if .Values.vminsert.resources }}
        resources:
        {{- with .Values.vminsert.resources }}
          limits:
            cpu: {{ .limit.cpu  | default "500m" }}
            memory: {{ .limit.memory | default "1024Mi" }}
          requests:
            cpu: {{ .request.cpu | default "50m" }}
            memory: {{ .request.memory | default "100Mi" }}
        {{- end }}
        {{- end }}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
{{- end }}