apiVersion: v1
data:
  blackbox.yaml: |
    modules:
        http_2xx:
            prober: http
            timeout: 10s
            http:
                no_follow_redirects: false
                preferred_ip_protocol: ip4
                valid_status_codes: [200]
                method: GET
                valid_http_versions: ["HTTP/1.1", "HTTP/2.0"]
                tls_config:
                    insecure_skip_verify: true
        icmp_ipv4:
            prober: icmp
            icmp:
              preferred_ip_protocol: ip4
kind: ConfigMap
metadata:
  labels:
    app: blackbox-config
  name: blackbox-config
  namespace: mon
