apiVersion: v1
kind: Service
metadata:
  labels:
    app: blackbox-exporter-core
  name: blackbox-exporter-core
  namespace: mon
spec:
  ports:
  - name: http
    port: 9115
    protocol: TCP
    targetPort: 9115
  selector:
    app: blackbox-exporter-core
  sessionAffinity: None
  type: ClusterIP