---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: alertmanager
  namespace: mon
spec:
  podManagementPolicy: OrderedReady
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: alertmanager
  serviceName: alertmanager
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: alertmanager
        stack: monitoring
      name: alertmanager
    spec:
      securityContext:
        runAsUser: 65534
        runAsGroup: 65534
        fsGroup: 65534
        runAsNonRoot: true
      containers:
      - image: prom/alertmanager:v0.24.0
        args:
          - "--config.file=/etc/alertmanager/alertmanager.yaml"
          - "--storage.path=/var/lib/alertmanager/data"
        imagePullPolicy: IfNotPresent
        name: alertmanager
        resources:
          limits:
            cpu: 300m
            memory: 500M
          requests:
            cpu: 50m
            memory: 50M
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/alertmanager/
          name: configs-files
        - mountPath: /var/lib/alertmanager/data
          name: data-alertmanager
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      volumes:
      - name: configs-files
        projected:
          defaultMode: 420
          sources:
          - configMap:
              name: alertmanager-config
          - configMap:
              name: alertmanager-template
  updateStrategy:
    rollingUpdate:
      partition: 0
    type: RollingUpdate
  volumeClaimTemplates:
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      creationTimestamp: null
      labels:
        app: alertmanager
      name: data-alertmanager
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
      storageClassName: standard
      volumeMode: Filesystem
    status:
      phase: Pending