apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: pushgateway
  name: pushgateway
  namespace: mon
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      name: pushgateway
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        prometheus.io.core/scrape: "true"
        prometheus.io/port: "9091"
      creationTimestamp: null
      labels:
        app: pushgateway
        component: pushgateway
        name: pushgateway
        stack: monitoring
    spec:
      containers:
      - image: prom/pushgateway:v1.6.1
        imagePullPolicy: IfNotPresent
        name: prometheus-pushgateway
        resources:
          limits:
            cpu: 300m
            memory: 600M
          requests:
            cpu: 50m
            memory: 300M
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30