apiVersion: v1
kind: Service
metadata:
  labels:
    app: pushgateway
  name: pushgateway
  namespace: mon
spec:
  ports:
  - name: pushgateway
    port: 9091
    protocol: TCP
    targetPort: 9091
  selector:
    app: pushgateway
  sessionAffinity: None
  type: ClusterIP