{{- if .Values.vmstorage.enable }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: {{ .Values.vmstorage.name }}
  name: {{ .Values.vmstorage.name }}
  namespace: {{ .Values.namespace }}
spec:
  podManagementPolicy: OrderedReady
  replicas: {{ .Values.vmstorage.replicas }}
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: {{ .Values.vmstorage.name }}
  serviceName: {{ .Values.vmstorage.name -}}-svc
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: {{ .Values.vmstorage.name }}
        stack: monitoring
    spec:
      containers:
      - args:
        - --retentionPeriod={{- .Values.vmstorage.args.retentionPeriod | default "1" }}
        - --storageDataPath={{- .Values.vmstorage.args.storagePath | default "/var/lib/data" }}
        {{- if .Values.vmstorage.extArgs }}
        {{- range .Values.vmstorage.extArgs }}
        - {{ . }}
        {{- end }}
        {{- end }}
        image: {{ .Values.vmstorage.image.repo -}}/{{- .Values.vmstorage.image.name -}}:{{- .Values.vmstorage.image.tag }}
        imagePullPolicy: IfNotPresent
        name: {{ .Values.vmstorage.name }}
        {{- if .Values.vmstorage.resources }}
        resources:
        {{- with .Values.vmstorage.resources }}
          limits:
            cpu: {{ .limit.cpu  | default "500m" }}
            memory: {{ .limit.memory | default "1024Mi" }}
          requests:
            cpu: {{ .request.cpu | default "150m" }}
            memory: {{ .request.memory | default "300Mi" }}
        {{- end }}
        {{- end }}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: {{ .Values.vmstorage.args.storagePath | default "/var/lib/data" }}
          name: data-victoria
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
  updateStrategy:
    rollingUpdate:
      partition: 0
    type: RollingUpdate
  volumeClaimTemplates:
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      creationTimestamp: null
      labels:
        app: vmstorage
      name: data-victoria
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: {{ .Values.vmstorage.storage.capacity | default "1Gi" }}
      storageClassName: {{ .Values.storageclass | default .Values.vmstorage.storage.class | default "standard" }}
      volumeMode: Filesystem
    status:
      phase: Pending
{{- end }}