{{- if .Values.grafana.enable }}
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.blackbox.name }}
  name: {{ .Values.blackbox.name }}
  namespace: {{ .Values.blackbox.namespace }}
spec:
  ports:
  - name: {{ .Values.blackbox.name }}
    port: 9115
    protocol: TCP
    targetPort: 9115
  selector:
    app: {{ .Values.blackbox.name }}
  type: ClusterIP
status:
  loadBalancer: {}
{{- end }}