apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: vmselect
  name: vmselect
  namespace: mon
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: vmselect
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: vmselect
        component: vmselect
        stack: monitoring
    spec:
      containers:
      - args:
        - --envflag.enable=true
        - --storageNode=vmstorage-0.vmstorage.mon.svc.cluster.local:8401
        image: victoriametrics/vmselect:v1.77.2-cluster
        imagePullPolicy: IfNotPresent
        name: vmselect
        resources:
          limits:
            cpu: 1500m
            memory: 36G
          requests:
            cpu: 100m
            memory: 512M
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
