apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "27"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"vmselect"},"name":"vmselect","namespace":"mon"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"vmselect"}},"template":{"metadata":{"labels":{"app":"vmselect","component":"vmselect","stack":"monitoring"}},"spec":{"affinity":{"nodeAffinity":{"preferredDuringSchedulingIgnoredDuringExecution":[{"preference":{"matchExpressions":[{"key":"node-role.kubernetes.io/monitoring","operator":"In","values":["true"]}]},"weight":100},{"preference":{"matchExpressions":[{"key":"node-role.kubernetes.io/worker","operator":"In","values":["true"]}]},"weight":80}]}},"containers":[{"args":["-envflag.enable"],"env":[{"name":"storageNode","value":"vmstorage-0.vmstorage.mon.svc.cluster.local:8401,vmstorage-1.vmstorage.mon.svc.cluster.local:8401,vmstorage-2.vmstorage.mon.svc.cluster.local:8401"}],"image":"infra/victoria-vmselect:v1.77.2-cluster-2022-06-14-6cffab81","imagePullPolicy":"IfNotPresent","name":"vmselect","resources":{"limits":{"cpu":"1.5","memory":"2G"},"requests":{"cpu":"0.1","memory":"256M"}}}],"imagePullSecrets":[{"name":"docker-registry-secret"}],"tolerations":[{"key":"role_maas","operator":"Exists"},{"key":"role_ceph","operator":"Exists"},{"key":"role_ceph_mon","operator":"Exists"},{"key":"role_ceph_osd","operator":"Exists"},{"key":"role_va","operator":"Exists"},{"key":"role_backend","operator":"Exists"},{"key":"role_monitoring","operator":"Exists"},{"key":"role_balancer","operator":"Exists"},{"key":"role_nvidia","operator":"Exists"},{"key":"node.kubernetes.io/not-ready","operator":"Exists"},{"key":"node.cloudprovider.kubernetes.io/uninitialized","operator":"Exists"}]}}}}
  creationTimestamp: "2022-01-28T10:29:34Z"
  generation: 29
  labels:
    app: vmselect
  name: vmselect
  namespace: mon
  resourceVersion: "1054789957"
  uid: 5aeaa1b8-d0c2-4ecc-89ba-36fd3ee1880e
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: vmselect
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: vmselect
        component: vmselect
        stack: monitoring
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - preference:
              matchExpressions:
              - key: node-role.kubernetes.io/monitoring
                operator: In
                values:
                - "true"
            weight: 100
          - preference:
              matchExpressions:
              - key: node-role.kubernetes.io/worker
                operator: In
                values:
                - "true"
            weight: 80
      containers:
      - args:
        - -envflag.enable
        - -memory.allowedPercent=100
        - -search.maxPointsPerTimeseries=45000
        - -search.maxQueryDuration=60s
        - -search.maxUniqueTimeseries=3000000
        env:
        - name: storageNode
          value: vmstorage-0.vmstorage.mon.svc.cluster.local:8401,vmstorage-1.vmstorage.mon.svc.cluster.local:8401,vmstorage-2.vmstorage.mon.svc.cluster.local:8401
        image: infra/victoria-vmselect:v1.77.2-cluster-2022-06-14-6cffab81
        imagePullPolicy: IfNotPresent
        name: vmselect
        resources:
          limits:
            cpu: 1500m
            memory: 36G
          requests:
            cpu: 100m
            memory: 512M
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: docker-registry-secret
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      tolerations:
      - key: role_maas
        operator: Exists
      - key: role_ceph
        operator: Exists
      - key: role_ceph_mon
        operator: Exists
      - key: role_ceph_osd
        operator: Exists
      - key: role_va
        operator: Exists
      - key: role_backend
        operator: Exists
      - key: role_monitoring
        operator: Exists
      - key: role_balancer
        operator: Exists
      - key: role_nvidia
        operator: Exists
      - key: node.kubernetes.io/not-ready
        operator: Exists
      - key: node.cloudprovider.kubernetes.io/uninitialized
        operator: Exists
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2022-01-28T10:29:34Z"
    lastUpdateTime: "2022-10-22T15:06:06Z"
    message: ReplicaSet "vmselect-f66457d75" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2023-10-12T08:15:50Z"
    lastUpdateTime: "2023-10-12T08:15:50Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 29
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
