apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app":"vmselect"},"name":"vmselect","namespace":"mon"},"spec":{"clusterIP":"None","ports":[{"name":"select","port":8481,"protocol":"TCP","targetPort":8481}],"selector":{"app":"vmselect"},"type":"ClusterIP"}}
  creationTimestamp: "2022-01-28T10:28:13Z"
  labels:
    app: vmselect
  name: vmselect
  namespace: mon
  resourceVersion: "384318809"
  uid: 4a829216-c453-44f8-aadf-f447ee342df8
spec:
  clusterIP: None
  clusterIPs:
  - None
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: select
    port: 8481
    protocol: TCP
    targetPort: 8481
  selector:
    app: vmselect
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
