{{ if .Values.pushgateway.enable }}
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.pushgateway.name }}
  name: {{ .Values.pushgateway.name }}
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - name: pushgateway
    port: 9091
    protocol: TCP
    targetPort: 9091
  selector:
    app: {{ .Values.pushgateway.name }}
  sessionAffinity: None
  type: ClusterIP
{{ end }}