apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: {{ .Values.prometheus.name }}
  name: {{ .Values.prometheus.name }}
spec:
  ports:
  - name: {{ .Values.prometheus.name }}
    port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
    app: {{ .Values.prometheus.name }}
  type: ClusterIP
status:
  loadBalancer: {}
